const questions = [
{
    id: 1,
    title: "Popular cuisines near me",
    infos: [
        "Bakery food near me . ",
        "Beverages food near me . ",
        "Burger food near me . ",
        "Cafe food near me . ",
        "Chinese food near me . ",
        "Coffee food near me . ",
        "Desserts food near me . ",
        "Ice Cream food near me . ",
        "Italian food near me . ",
        "Mithai food near me . ",
        "Momos food near me . ",
        "Mughlai food near me . ",
        "North Indian food near me . ",
        "Pasta food near me . ",
        "Pizza food near me . ",
        "Rajasthani food near me . ",
        "Sandwich food near me . ",
        "Shake food near me . ",
        "South Indian food near me . ",
        "Street food near me . ",
    ],
},
{
    id: 2,
    title: "Popular restaurant types near me",
    infos: [
        "Bakeries near me . ",
        "Bars food near me . ",
        "Beverage Shops near me . ",
        "Bhojanalya near me . ",
        "Cafés near me . ",
        "Clubs near me . ",
        "Dessert Parlors near me . ",
        "Dhabas near me . ",
        "Fine Dining near me . ",
        "Food Courts near me . ",
        "Food Trucks near me . ",
        "Kiosks near me . ",
        "Lounges near me . ",
        "Paan Shop near me . ",
        "Quick Bites near me . ",
        "Sweet Shops near me . ",
    ],
},
{
    id: 3,
    title: "Top Restaurant Chains",
    infos: [ 
        "Pizza Hut",
    ],
},
];
export default questions;